spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8
      username: root
      password: xiehua123
      driver-class-name: com.mysql.cj.jdbc.Driver